### ISSUE TITLE
Support for Jupyter

### ISSUE THREAD

**Issue by pierrecottinINO** [elazarcoh/simply-view-image-for-python-debugging#11]
This extension works well for Python. Would it be possible to make it work inside a Jupyter notebook?

**Comment by elazarcoh** [comment]
Hmm... possibly. Depends on what you want, exactly.
Can you describe the functionality you'd like to have inside the notebook?

**Comment by pierrecottinINO** [comment]
When running a cell in debug, I would like to be able to select a variable (an image, a 1D or 2D array) and display the content as an image or a graph. The watch feature is also nice but with a notebook, it does not detect the image variables.

Pierre Cottin

De : elazarcoh ***@***.***>
Envoyé : 27 janvier 2022 16:14
À : elazarcoh/simply-view-image-for-python-debugging ***@***.***>
Cc : COTTIN Pierre ***@***.***>; Author ***@***.***>
Objet : Re: [elazarcoh/simply-view-image-for-python-debugging] Support for Jupyter (Issue #11)


Hmm... possibly. Depends on what you want, exactly.
Can you describe the functionality you'd like to have inside the notebook?

-
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Felazarcoh%2Fsimply-view-image-for-python-debugging%2Fissues%2F11%23issuecomment-1023644049&data=04%7C01%7Cpierre.cottin%40ino.ca%7Cfd4c141de23c4099664108d9e1d9f80e%7C04225a60d9a0456fae3bf086c6de0f24%7C1%7C0%7C637789148548722730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xE2bsiwkOoEN1%2FJ8QC6zuM%2BxbeovnCpDrA5A0Wobtr4%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT4NIUQUZQLZZWYJKQI3GE3UYGYSJANCNFSM5M7BI2RA&data=04%7C01%7Cpierre.cottin%40ino.ca%7Cfd4c141de23c4099664108d9e1d9f80e%7C04225a60d9a0456fae3bf086c6de0f24%7C1%7C0%7C637789148548722730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FPVTHhRAAp6f%2FLB0SFnD8sz2cByCV70l3b1S4L2HSmk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpierre.cottin%40ino.ca%7Cfd4c141de23c4099664108d9e1d9f80e%7C04225a60d9a0456fae3bf086c6de0f24%7C1%7C0%7C637789148548722730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GyG%2FlrdaKUlimch7pBj%2BgH%2BzcXy3v9cnemMdH9Y21HE%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpierre.cottin%40ino.ca%7Cfd4c141de23c4099664108d9e1d9f80e%7C04225a60d9a0456fae3bf086c6de0f24%7C1%7C0%7C637789148548722730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=W4rb9DRiL6HV0eIPILemD3ZPc75C7v5%2FvmRjS%2Bgnz5c%3D&reserved=0>.

**Comment by elazarcoh** [comment]
Thanks. I'll look into it.

**Comment by elazarcoh** [comment]
This should be available as a pre-release. 
I'm going to do more testing. Would love to hear your feedback.

**Comment by pierrecottinINO** [comment]
I have tried the pre-release version with this simple Jupyter notebook (btw I'm using the Jupyter extension in VSCode):
```
import numpy as np 
import plotly.express as px

img_rgb = np.array([[[255, 0, 0], [0, 255, 0], [0, 0, 255]],
                    [[0, 255, 0], [0, 0, 255], [255, 0, 0]]
                   ], dtype=np.uint8)
fig = px.imshow(img_rgb)
fig.show()
```
but when I break after the img_rgb definition, I do not get the yellow bulb neither the variable in the Watch tab. With the same code directly in Python, it works.

**Comment by elazarcoh** [comment]
Ahhh a Jupyter notebook... I've tested only with IPython cells...
OK, thanks for the feedback. I'll work on it, hopefully it'll be possible. Stay tuned.

**Comment by elazarcoh** [comment]
@pierrecottinINO 
I think it should all work now in a Jupyter notebook. Check out version 2.1.5 pre-release.

**Comment by pierrecottinINO** [comment]
It works exactly as expected. Great job.
Thank you very much for this upgrade.

Pierre Cottin, 418-657-7406 x2302

De : elazarcoh ***@***.***>
Envoyé : 31 janvier 2022 15:40
À : elazarcoh/simply-view-image-for-python-debugging ***@***.***>
Cc : COTTIN Pierre ***@***.***>; Mention ***@***.***>
Objet : Re: [elazarcoh/simply-view-image-for-python-debugging] Support for Jupyter (Issue #11)


@pierrecottinINO<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FpierrecottinINO&data=04%7C01%7Cpierre.cottin%40ino.ca%7Ce083efb1e7ed408ec86908d9e4f9d996%7C04225a60d9a0456fae3bf086c6de0f24%7C1%7C0%7C637792584016907699%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Of5hrpyHewCrojkjWXM8LQHfg7HTJRSGWLSbAeAKCfU%3D&reserved=0>
I think it should all work now in a Jupyter notebook. Check out version 2.1.5 pre-release.

-
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Felazarcoh%2Fsimply-view-image-for-python-debugging%2Fissues%2F11%23issuecomment-1026188740&data=04%7C01%7Cpierre.cottin%40ino.ca%7Ce083efb1e7ed408ec86908d9e4f9d996%7C04225a60d9a0456fae3bf086c6de0f24%7C1%7C0%7C637792584017063901%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aD5XLeMPMEoEYrUZsURSlboLZ5S0V5RnaoKnGrWhSGg%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT4NIUSHERCTBO3CEFGPXVLUY3XR7ANCNFSM5M7BI2RA&data=04%7C01%7Cpierre.cottin%40ino.ca%7Ce083efb1e7ed408ec86908d9e4f9d996%7C04225a60d9a0456fae3bf086c6de0f24%7C1%7C0%7C637792584017063901%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JVozhWK3pAsdWCSnK1sz20wiWfaB3Wo9kM5aoCHRIfA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpierre.cottin%40ino.ca%7Ce083efb1e7ed408ec86908d9e4f9d996%7C04225a60d9a0456fae3bf086c6de0f24%7C1%7C0%7C637792584017063901%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=35Gy2ss%2F7VavoT%2Fx1fA7evgD2F3fzPbCektyQcrURmg%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpierre.cottin%40ino.ca%7Ce083efb1e7ed408ec86908d9e4f9d996%7C04225a60d9a0456fae3bf086c6de0f24%7C1%7C0%7C637792584017063901%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=djILRfERojvkHD5%2F2pkKl20Wd85%2BBgQtYW2CZLGvjVw%3D&reserved=0>.
