### ISSUE TITLE
extension stopped displaying images during debug

### ISSUE THREAD

**Issue by DolevBria** [elazarcoh/simply-view-image-for-python-debugging#14]
Issue Type: <b>Bug</b>

I updated my vscode and no longer able to display images using the extension.

Extension version: 2.2.0
VS Code version: Code 1.64.0 (Universal) (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:17.224Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1064-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 5819c93b-df7c-44ab-9a77-d451747848ac|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: [DEV] Dolev CPU|
|OS|Linux x64 5.4.0-1064-aws|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (4 x 2300)|
|Memory (System)|15.63GB (0.88GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vs360:30404995
vsrem710:30416614
vscop841cf:30434590
vscscmwlcmc:30433760

```

</details>

**Comment by elazarcoh** [comment]
@DolevBria 
Can't reproduce (tested with Windows and Ubuntu).
Do you see an error notification?

Do this setting is checked?
![image](https://user-images.githubusercontent.com/28874499/152988282-9c2ccb45-65b6-4441-ab06-802dbb3fac67.png)

If it checked, please delete `/tmp/svifpd` and see if it helps.

**Comment by DolevBria** [comment]
I tried it, also tried unchecking this setting, still doesn't work with version 2.2.0.

**Comment by elazarcoh** [comment]
Do you see the lightbulb near variables?

Do the Image Watch window works? (e.g. showing any variable)
(make sure to add "images" to the image watch settings, if you don't have it already)

**Comment by DolevBria** [comment]
The lightbulb doesn't appear on version 2.2.0.
The variable (which is a PIL image and ndarray representing RGB Image) is on my watch window (it is not None).
That setting is checked
![image](https://user-images.githubusercontent.com/91606928/153004604-abc0fdff-8a96-46d8-b522-1a387aa1afda.png)

**Comment by elazarcoh** [comment]
I mean in this window:
![image](https://user-images.githubusercontent.com/28874499/153006771-a97439a8-de77-4c60-89f7-a29fda4a16f6.png)

Also, can you share a minimal example that doesn't work for you?

**Comment by DolevBria** [comment]
The IMAGE WATCH menu appears empty on version 2.2.0 and has my images on 2.1.1

**Comment by DolevBria** [comment]
I've tried to reproduce the problem on a minimal example, however I'm not able to. I can only say that the image watch menu is turning out empty, and the image is around 1000 * 2000 pixels represented as PIL image.

**Comment by elazarcoh** [comment]
Just to make sure:
You tried to reproduce with a minimal example, and everything seems to be working on that example?

If so, I have a couple of questions:
1. Is that a simple python debug, or you're using IPython cells?
2. Do you have a multi-threaded code?
3. Can you try run the `Update Frame ID` command in the Commands Palette while debugging, and see if it changes anything?
