### ISSUE TITLE
Feature request: Show plots directly from variable list

### ISSUE THREAD

**Issue by Christopher22** [elazarcoh/simply-view-image-for-python-debugging#17]
Hey @elazarcoh,
first of all: Thank you for the amazing extension!

[Visual Studio Code supports a command "View value in Data viewer" when performing a right-click on a Numpy.ndarray or pandas.Dataframe variable in the variable list](https://devblogs.microsoft.com/python/python-in-visual-studio-code-january-2021-release/). Might it be possible for you to add a similar command "View object as plot" in the context menu for matplotlib.Axes and matplotlib.Figure objects, too?

Unfortunately, I have no experience with writing VS Code extensions whatsoever. However, if you give me some hints, I may be able to create a Pull Request myself, too.

**Comment by elazarcoh** [comment]
Hi,
There's already support for matplotlib objects during debug, you can access it via the light bulb when you hover over a variable.
Maybe that is not what you requested. If not, please clarify. 
Thanks.

**Comment by elazarcoh** [comment]
oh now I understand.
I'll look into it.
but you can use the image watch view for it.

**Comment by Christopher22** [comment]
You are right, the image watch view works well in that setup. 
It is merely a (low-priority) convenience function given users commonly working with the variable view might expect it there, too. I just can not estimate the required amount of work.

**Comment by elazarcoh** [comment]
Finally I managed to dig into it.

As far as I can tell, I can add a context menu entry to all variables, but not to a subset. That means every variable, even `i = 0`, would have this context menu entry.
I'm not sure if that's good solution. 

The python extension adds this to only a valid variables, by sending `__vscodeVariableMenuContext ` to the debug adapter, which is something I can't inject into, unfortunately.

**Comment by Christopher22** [comment]
Thank you for investigating!

**Comment by elazarcoh** [comment]
So apparently it is possible! I just needed to dig into the jupyter extension to figure it out. Implemented at #25 .

For now, it seems I can't support anything that is have the "View value in Data viewer" (because I would overwrite it). Maybe I'll open a PR to Jupyter, to allow multiple context values. We'll see.

I hope to make a pre-release in a day or two. Stay tuned.
