### ISSUE TITLE
Image watch not working properly with numpy arrays

### ISSUE THREAD

**Issue by cattaneod** [elazarcoh/simply-view-image-for-python-debugging#19]
Thank you very much for this extension, it's really useful!

I have an issue with the image watch feature and numpy arrays: if i hover a variable name and press "view image", everything works fine (first attached image). However, if i press "view" on the same variable name on the image watch box, the image is not rendering properly (second attached image).

This only happens with numpy arrays, with torch tensors everything works fine.

![image](https://user-images.githubusercontent.com/11426917/176429938-a5277fcb-5e43-4d86-91dd-b873f2d5c5ed.png)
![image view](https://user-images.githubusercontent.com/11426917/176430108-14ab4c50-172c-48a0-8323-71955e65cc3c.png)

**Comment by elazarcoh** [comment]
yeah.. it seems to think it's a tensor rather than an image. I'll have to figure out a way to differentiate the two.

**Comment by elazarcoh** [comment]
There's a pre-release version that addresses this now. Please check it out and tell me what you think.

**Comment by cattaneod** [comment]
Now it's working correctly, thank you!

**Comment by cattaneod** [comment]
Update: now the image is visualized correctly, but the "track" feature doesn't work anymore.

**Comment by elazarcoh** [comment]
Sorry for the delay. The tracking works for me well. nothing changed in that regard.
The only change I expect to have, is for something that can be interpreted both as a single image and a tensor (e.g. numpy array with shape of (256, 256, 3)). In this case, it would consider it as a single image, and save it as such.

**Comment by elazarcoh** [comment]
If that still relevant, please open a new issue for it.
(I noticed something like this in some rare occurrences, but it seems to be vscode issue of not updating the view. The image was generated as expected)
