### ISSUE TITLE
Bulb sign doesn't appear anymore while clicking on image variable

### ISSUE THREAD

**Issue by xenia-kra** [elazarcoh/simply-view-image-for-python-debugging#21]
vscode version: Version: 1.68.1 (Universal)
extension: last stable
I think it stopped working somehow after one of the vscode updates and never came back functioning again.
What could be a reason?

I've tried also using john-guo version. In this case, the bulb appears after ±5 minutes delay. Which is also very strange.

**Comment by elazarcoh** [comment]
It's possibly something to do with very slow communication with the debugger. You can try to turn on logging, `svifpd.debug` in the settings, maybe it can give us a clue (though sadly it's not very thorough). 

Can you confirm whether that's a possibility? Because on my side it works just fine.

**Comment by xenia-kra** [comment]
should I see any additional debug output after adding it?
if yes, so there isn't any.

**Comment by elazarcoh** [comment]
In the Output tab:
![image](https://user-images.githubusercontent.com/28874499/177106966-5e464077-ba4b-40e1-b1f0-e9763ae553a5.png)

**Comment by xenia-kra** [comment]
I don't have this section in the output window.
Only "Extensions" and this shows me a blank output
<img width="1556" alt="image" src="https://user-images.githubusercontent.com/81739495/177112892-28d704d0-8d6c-48a2-b639-a177d4b24f69.png">

**Comment by elazarcoh** [comment]
Hmm... try with the pre-release version, then. It's possible I didn't add it to the stable version yet.

**Comment by xenia-kra** [comment]
Ok. Great. Finally, I do see some error
"evaluate initExpression result: "
{
  "name": "Error",
  "message": "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name '_python_view_image_mod' is not defined\n"
}

Any clue what it means?

**Comment by elazarcoh** [comment]
Yes, that's helpful.
If you can share the entire log, it would help.

**Comment by xenia-kra** [comment]
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/81739495/177257131-9744ebe5-c20e-4cc7-a774-9a9b2eea0809.png">
The same error is being repeated when I click on the image variable.

**Comment by elazarcoh** [comment]
Okay. That's a bit weird.
What python version you use?
Please try to run this code and let me know if it works.

```python
try:
    _python_view_image_mod
except NameError:
    
    from types import ModuleType
    _python_view_image_mod = ModuleType('python_view_image_mod', '')

print(_python_view_image_mod)
```

**Comment by xenia-kra** [comment]
Python 3.8.10
I'm getting <module 'python_view_image_mod'> (after handling exception)

**Comment by elazarcoh** [comment]
Hmm.. for now I don't have a clue for what's going on. The `initExpression` is the above code (with additional code that should not affect the existence of `_python_view_image_mod`).

More information that might shed some light (though I doubt it):
* OS
* Python extension version

I'm not familiar with `VSCode Universal`, is that the standard version for VSCode on Mac? (I don't have a Mac, so testing if it's related isn't possible. Then again, I doubt it related.)

**Comment by elazarcoh** [comment]
Do you debug locally? Is it over ssh? Something else that you have in mind that might be related?

**Comment by xenia-kra** [comment]
os: ubuntu-jammy-22.04 I'm using it over ssh, bit it also doesn't work locally
python ext:2022.8.1 -last stable
VSCode universal is the standard version for Mac

**Comment by elazarcoh** [comment]
Closing this. Hopefully next release will fix most bugs I had.
If still needed, please open a new issue.
