### ISSUE TITLE
variable in debug

### ISSUE THREAD

**Issue by acgull** [elazarcoh/simply-view-image-for-python-debugging#22]
Is there any way to view images/arrays that I create using the debug console?
I don't see any bulb there, and there doesn't seem to be a way to view as image using the variable view.

**Comment by elazarcoh** [comment]
If you're using the Image Watch window (it's in the debug window), it should be possible. You should be able to create the image in the debug console, then refresh the image watch view, and it should appear there.

If that doesn't work, let me know.
