### ISSUE TITLE
Add a shortcut to run the viewer

### ISSUE THREAD

**Issue by YoniChechik** [elazarcoh/simply-view-image-for-python-debugging#34]
How can I add a shortcut to mark some variable and view it? Can be faster than with the bulb...

Really appreciate the work you've done on this app :)

**Comment by elazarcoh** [comment]
There should be an `alt+ctrl+q` shortcut. But you can add more shortcuts to the existing commands as you see fit, like any other VSCode shortcuts.
Does it work your needs?

**Comment by YoniChechik** [comment]
Thanks!
