### ISSUE TITLE
View images within an array of images

### ISSUE THREAD

**Issue by kapsyst** [elazarcoh/simply-view-image-for-python-debugging#37]
Is there a way to do this? I can't get the bulb to appear for arrays (works fine for individual images).

Thank you for writing a very useful plugin, by the way!

**Comment by kapsyst** [comment]
To be a bit more precise, here are the data types of the array/image I'm trying to display:

```
type(images)
<class 'list'>
images[0]
<PIL.Image.Image image mode=RGB size=256x256 at 0x7F73993EE0D0>
```

**Comment by elazarcoh** [comment]
The only way to achieve this currently, is to write somewhere in the code `images[0]`, and select it. A lightbulb should appear.

**Comment by kapsyst** [comment]
@elazarcoh I see, I'll give that a go!

**Comment by elazarcoh** [comment]
New Pre-Release is available, which supports expressions in the watch view!
Please give it a try. I would love to hear feedback on the release.

**Comment by kapsyst** [comment]
Great, thanks @elazarcoh! Will give it a go.

**Comment by elazarcoh** [comment]
v3 is released, now you can use the Expressions feature.
