### ISSUE TITLE
display numpy.array(dtype=numpy.bool) -- more helpful message or documentation?

### ISSUE THREAD

**Issue by drjasonharrison** [elazarcoh/simply-view-image-for-python-debugging#43]
When I try to "View Image" on a numpy.array(dtype=numpy.bool) I get the following error:

```
! preferred backend Standalone can't be used, as it 
depends on 'numpy'. will try to fall back to other 
method.
```

![image](https://user-images.githubusercontent.com/6044603/205143240-4734adec-3baf-49cb-b17a-41d620925cf8.png)

I'm using a virtualenv, can the extension access the numpy that I have installed in that environment, or is it trying to access a global numpy or is the problem that numpy isn't installed?

Why can't "backend Standalone" be used?

**Comment by elazarcoh** [comment]
yes, that makes sense... The main issue is that I don't get helpful error messages from python when some execution fails. I'm currently working on a major refactoring, and I'm already taking it into account.
Thanks!

**Comment by elazarcoh** [comment]
And for the actual question, it doesn't know how to save bool type. This is another thing I intend to fix on the next release.

**Comment by drjasonharrison** [comment]
so, if I use the debugger to cast to another type...yes that works after refreshing the "IMAGE WATCH" pane

**Comment by elazarcoh** [comment]
New Pre-Release is available, which fixes this (along with more improvements).
Please give it a try. I would love to hear feedback on the release.

**Comment by elazarcoh** [comment]
v3 is released. This issue is handled in it.
