### ISSUE TITLE
Feature request: toggle image normalization

### ISSUE THREAD

**Issue by YoniChechik** [elazarcoh/simply-view-image-for-python-debugging#52]
First let me say that this is an amazing extansion! I'm using it almost daily since installed, and brought more people on board :)

As a Computer Vision engineer I often want to view uint8 (0-255)/ float (0-1) images without normalization, so here I've changed the extension default- this is importent for me to view changes in image brightness and much more. But sometimes I view some irregular images (e.g. uint8 masks with indices of 0-9), and then I do want the normalization.

I suggest that there would to button to view images, one with normalization and one without. Another suggestion can be to have the same arrangment, but add another option via right click, so the option to alternate between states will be easier.

**Comment by elazarcoh** [comment]
Sounds reasonable enough. 
For your use case, does it need to be normalized/raw on a variable basis (as opposed to a global setting affecting all variables)?
For a variable basis, I'm more inclined towards one of the following solutions:
1. add a right click to the variable entry in the tree
2. add a way to change it on the subtree of a variable
3. orthogonally to the above, I can add a heuristic way of deciding whether normalizing is better or worse for a given image (e.g. decide based dtype and min/max values).

I don't want to add a separate inline button, as it's already kinda clattered as is (for my taste, at least).

Would love to hear your thoughts, and any other suggestions.

**Comment by elazarcoh** [comment]
This is on pre-release! please check it out.

**Comment by YoniChechik** [comment]
I've used the pre-release for the last week because of the debugpy bug and I must say that it's AMAZING!!! Thank you so much for the hard work!

Hope it will be released soon as a regular release
