### ISSUE TITLE
support to show a data table of a ndarray like pycharm

### ISSUE THREAD

**Issue by MYTHOFLEGEND** [elazarcoh/simply-view-image-for-python-debugging#55]
can you add a function to show a data table of ndarray like pycharm?

sometimes I need to check every value of a ndarray or an image

thanks!

**Comment by elazarcoh** [comment]
I'm currently working on an improved viewer that would do exactly it. Problem is it would take me a while to implement it.

I do have a relatively simple way to extend my extension, though it would require you to build the extension from source to implement it, as I'm not exporting this functionality right now.
If you want to do that, I can guide you through it.

**Comment by elazarcoh** [comment]
This is on pre-release! please check it out.

**Comment by MYTHOFLEGEND** [comment]
I will have a try, thank you very much!
