### ISSUE TITLE
Error saving viewable of type torch_tensor: RuntimeError: result type Float cant be cast to the desired output type Byte

### ISSUE THREAD

**Issue by genghisun** [elazarcoh/simply-view-image-for-python-debugging#58]
error when view a pytorch tensor
![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/26201304/fed806ff-13f9-48de-b899-e3ea098ba76c)
`Error saving viewable of type torch_tensor: RuntimeError: result type Float cant be cast to the desired output type Byte`
what does this mean?

**Comment by elazarcoh** [comment]
I think it must be cast to float before saving: `images[:5].float()`.
It's possible for me to cast it automatically, but I don't know if it's the best solution.
I'm not using torch that much. What do you think? does casting should be the default behavior?

**Comment by genghisun** [comment]
Thanks! The image is successfully displayed after adding `.float()`
But I don't understand why we have to do type conversion here. As far as I know, `torchvision.utils.save_image` accept image tensor of type uint8.

**Comment by elazarcoh** [comment]
I don't know. This is the code I'm using to save the given tensor:
```python
def save(path, obj, normalize=True, pad=10, *args, **kwargs): 
             import torchvision 
  
             pad_value = 255 
             torchvision.utils.save_image( 
                 obj, 
                 path, 
                 normalize=normalize, 
                 pad_value=pad_value, 
                 padding=pad, 
             )
```
Does this work for you without converting to float?

**Comment by genghisun** [comment]
Oh, after testing, `torchvision.utils.save_image` cant handle uint8 input, cause it will normalize tensor to range [0,1], so it requires a float type input.
I think it‘s good to convert the type to float by default. like:
<pre>
torchvision.utils.save_image( 
    obj<b>.float()</b>, 
    path, 
    normalize=normalize, 
    pad_value=pad_value, 
    padding=pad, 
)
</pre>
