### ISSUE TITLE
View Image apparently stopped working since update to VS Code 1.86.0 (Universal) Mac

### ISSUE THREAD

**Issue by alvarobasi** [elazarcoh/simply-view-image-for-python-debugging#81]
Good morning.

Since the latest update to VS Code 1.86.0 (Universal), Image Watch stopped showing the images in the Variables section of the Image Watch debug window. 
![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/36459941/2d4b289a-7a97-4702-8a58-c0a4fafd8448)

I've tried either with the latest release or with the current pre-release version v3.0.17 (pre-release). Any ideas what could be going on there? 

Thanks in advance!

**Comment by elazarcoh** [comment]
Hi,
Thanks for reporting. 
Can you please attach the log of the extension?
First, open the settings and turn on the logging: 
![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/28874499/0de525ad-095c-4f25-b73e-5ae239c5ffd0)
Then copy the output from here:
![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/28874499/29472734-2970-4f76-bd6a-3b7b40da68d3)

Maybe we can find some clue there

**Comment by alvarobasi** [comment]
Thanks for the response. I've tried your suggestions. Even if I place some images in memory these are the only logs I see.
`"[Trace]" "Activating extension"
"[Debug]" "Allowed plugins" []
"[Debug]" "Using tmp folder for saving files"
"[Debug]" "saveDir: /var/folders/kz/y87w42210wxd5l97jk3_h2300000gn/T/svifpd/images"
"[Debug]" "Registering debug adapter tracker for python"
"[Debug]" "Registering debug adapter tracker for python-Jupyter"
"[Debug]" "Registering code actions provider (the lightbulb)"
"[Debug]" "Registering hover provider (for shape info)"
"[Debug]" "Registering image watch tree view provider"
"[Info]" "SocketServer started on port 53382"`

**Comment by elazarcoh** [comment]
Try to set it to "verbose" output.

**Comment by alvarobasi** [comment]
I've set the config to verbose as you explained above, if that's what you mean.
![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/36459941/ded2f6dc-7204-4e4d-9708-5c63588b8825)

**Comment by elazarcoh** [comment]
Yeah that's what I meant. I'll try to look into it. I don't have a Mac so I can't reproduce. On windows it works in this version.
Can you try it with the insiders version of vscode?

**Comment by elazarcoh** [comment]
Can you try to run the 
![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/28874499/360a63b5-9609-4c66-a9b8-070f67c6628e)
Command in the command palette during debug and look if there is any additional output?

**Comment by elazarcoh** [comment]
Thanks. It seems that the debugger is not registered with the extension for some reason. I'll try to dig into it. Not sure what could have happen. 
If it is possible, can you check whether this extension works for you? We both using the same method for registering with the debugger.
https://github.com/hediet/vscode-debug-visualizer
usage example: https://github.com/hediet/vscode-debug-visualizer/tree/master/demos/python

**Comment by alvarobasi** [comment]
The extension seems to be working. I think it might have something to do with the python debugger, is giving some problems recently. I know someone having reset the launch.json and View Image suddenly stopped working for him. Always VS Code 1.86.0 and same output in the View Image Debug.
![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/36459941/80c4859f-3fde-4904-bcdb-4564379f13ef)

**Comment by alvarobasi** [comment]
Hi! We managed to make View Image work again. It is related to the new python debugger recently added to 1.86. Changing the debugger in the launch.json file back to "python" is the solution.
![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/36459941/33d9bebe-d200-4605-b0b3-6cf9a8fab1bc)
![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/36459941/2b1609e3-83b8-4114-b8ff-f6489eadf623)

**Comment by elazarcoh** [comment]
Great! What was the value before? Maybe I can register the debugger with this type as well

**Comment by alvarobasi** [comment]
They moved from "python" to "debugpy". There is a warning saying it will be deprecated soon.

**Comment by elazarcoh** [comment]
Oh okay. Thanks.

**Comment by elazarcoh** [comment]
Fixes by #83.
Will try to make a (pre-)release soon.
