### ISSUE TITLE
can you give an option for reversing the direction of the mouse scrolling

### ISSUE THREAD

**Issue by MYTHOFLEGEND** [elazarcoh/simply-view-image-for-python-debugging#86]
I realized that there is a new feature in pre release version that can adjust the size of image by mouse whell scrolling, but the direction is contrary for me, can you please give an option for reversing the direction of the mouse scrolling

**Comment by elazarcoh** [comment]
Sure. It might take a bit of time to implement though.

**Comment by elazarcoh** [comment]
Not so much time as I expected :)
Can be controlled via the new setting:
![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/28874499/18702454-feb7-407c-998e-3d80fbd20570)
